# Generated by Django 4.2.2 on 2023-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
