# Generated by Django 4.2.2 on 2023-06-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='payment_status',
        ),
    ]
