# Generated by Django 4.2.2 on 2023-06-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_payment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='created',
        ),
    ]
